# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: AcerIncorporated.AcerProductRegistration
PackageVersion: 2022.11.08.1448
Installers:
- InstallerUrl: http://10.36.22.111:8180/HungCharlie/prodreginstallers/-/raw/main/2b39f60c02594a838bf4de7851532b59.msix
  Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerSha256: B95069BC4B6494E942DA6D61A05E046CAABF4565FCC54A6A170CA6682728A30A
  SignatureSha256: 74117820CE58C6CEC7EFED928EBB99F27C26156A2E51458FE620C38A81F6946F
  PackageFamilyName: AcerIncorporated.AcerRegistration_48frkmn4z8aw4
ManifestType: installer
ManifestVersion: 1.2.0

