# Created using wingetcreate 1.2.0.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: AcerIncorporated.AcerProductRegistration
PackageVersion: 2.0.3030.0
PackageLocale: en-US
Publisher: Acer Incorporated
PackageName: Acer Product Registration
License: MIT License
ShortDescription: Acer Product Registration Installer
ManifestType: defaultLocale
ManifestVersion: 1.4.0
